import type { ClassManagementRepository } from '../data/studentRepository.js';
import type { GroupLayoutRepository } from '../data/groupLayoutRepository.js';
import type { SeatingLayoutRepository } from '../data/seatingLayoutRepository.js';
import { filterRoster, maskProfileField, profileGroups, sensitiveProfileKeys, type ProfileField, type RosterStudent } from '../domain/student.js';
import { exactStudentLookup } from '../imports/importValidation.js';
import { parseGroupTemplate } from '../imports/groupTemplateParser.js';
import { parseSeatingTemplate } from '../imports/seatingTemplateParser.js';
import type { WorkbookRows } from '../imports/templateContracts.js';
import { printLayout } from '../printing/layoutPrint.js';
import type { GroupLayout } from '../domain/group-layout.js';
import type { SeatingLayout } from '../domain/seating-layout.js';

const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char] as string));

export class ClassManagementPage {
  private students: RosterStudent[] = [];
  private selectedId: string | null = null;
  private query = '';
  private tab: 'roster' | 'info' | 'groups' | 'seating' = 'roster';
  private profile: Record<string, string> | null = null;
  private revealed = new Set<string>();
  private savedGroupLayout: GroupLayout | null = null;
  private draftGroupLayout: GroupLayout | null = null;
  private savedSeatingLayout: SeatingLayout | null = null;
  private draftSeatingLayout: SeatingLayout | null = null;
  private groupErrors: string[] = [];
  private seatingErrors: string[] = [];
  private groupSaveState: 'idle' | 'saving' | 'saved' | 'error' = 'idle';
  private seatingSaveState: 'idle' | 'saving' | 'saved' | 'error' = 'idle';
  constructor(private readonly root: HTMLElement, private readonly repository: ClassManagementRepository, private readonly groups?: GroupLayoutRepository, private readonly seating?: SeatingLayoutRepository) {}

  async mount() { await this.loadRoster(); const classId = await this.repository.getClass8Id(); if (classId) { this.savedGroupLayout = await this.groups?.getCurrent(classId) || null; this.savedSeatingLayout = await this.seating?.getCurrent(classId) || null; } this.render(); }
  private async loadRoster() { this.students = await this.repository.listRoster8(); this.selectedId = this.students[0]?.id ?? null; }
  private async select(id: string) { this.selectedId = id; this.revealed.clear(); this.profile = null; this.tab = 'info'; this.render(); try { this.profile = await this.repository.getProfile(id); } catch { this.profile = null; } this.render(); }
  private render() {
    const filtered = filterRoster(this.students, this.query);
    if (this.selectedId && !filtered.some((item) => item.id === this.selectedId)) this.selectedId = filtered[0]?.id ?? null;
    this.root.innerHTML = `<div class="class-management" data-testid="class-management"><div class="content-head"><div><h2>2025级8班班级管理</h2><p>花名册、学生信息、分组表与座次表。</p></div></div><div class="tabbar" role="tablist"><button class="${this.tab === 'roster' ? 'active' : ''}" data-tab="roster">花名册</button><button class="${this.tab === 'info' ? 'active' : ''}" data-tab="info">学生信息</button><button class="${this.tab === 'groups' ? 'active' : ''}" data-tab="groups">分组表</button><button class="${this.tab === 'seating' ? 'active' : ''}" data-tab="seating">座次表</button></div>${this.tab === 'roster' ? this.renderRoster(filtered) : this.tab === 'info' ? this.renderInfo(filtered) : this.tab === 'groups' ? this.renderGroups() : this.renderSeating()}</div>`;
    this.root.querySelectorAll<HTMLElement>('[data-tab]').forEach((button) => button.addEventListener('click', () => { this.tab = button.dataset.tab as 'roster' | 'info' | 'groups' | 'seating'; this.revealed.clear(); this.render(); }));
    const search = this.root.querySelector<HTMLInputElement>('[data-student-search]');
    search?.addEventListener('input', () => { this.query = search.value; this.render(); });
    this.root.querySelectorAll<HTMLElement>('[data-student-id]').forEach((row) => row.addEventListener('click', () => void this.select(row.dataset.studentId!)));
    this.root.querySelectorAll<HTMLElement>('[data-reveal]').forEach((button) => button.addEventListener('click', () => { const key = button.dataset.reveal!; this.revealed.has(key) ? this.revealed.delete(key) : this.revealed.add(key); this.render(); }));
    this.root.querySelector('[data-template-download]')?.addEventListener('click', () => this.downloadTemplate(this.tab));
    this.root.querySelector<HTMLInputElement>('[data-layout-file]')?.addEventListener('change', (event) => void this.handleUpload((event.target as HTMLInputElement).files?.[0]));
    this.root.querySelector('[data-layout-confirm]')?.addEventListener('click', () => void this.confirmLayout());
    this.root.querySelector('[data-layout-cancel]')?.addEventListener('click', () => { this.cancelCurrentDraft(); });
    this.root.querySelector('[data-layout-print]')?.addEventListener('click', () => this.printCurrent());
  }
  private renderRoster(filtered: RosterStudent[]) { return `<div class="toolbar"><input class="input grow" data-student-search placeholder="搜索姓名、身份证件号、省学籍辅号或准考证号" value="${esc(this.query)}"><span class="muted">${filtered.length} 人</span></div>${filtered.length ? `<section class="panel panel-pad"><div class="table-wrap"><table class="data-table"><thead><tr><th>姓名</th><th>身份证件号</th><th>省学籍辅号</th><th>准考证号</th></tr></thead><tbody>${filtered.map((student) => `<tr><td><button class="button quiet" data-student-id="${esc(student.id)}"><strong>${esc(student.displayName)}</strong></button></td><td>${esc(student.identityDocumentNo || '未填写')}</td><td>${esc(student.provincialStudentNo || '未填写')}</td><td>${esc(student.examNo || '未填写')}</td></tr>`).join('')}</tbody></table></div></section>` : '<section class="panel panel-pad"><div class="empty">未找到符合条件的学生</div></section>'}`; }
  private renderInfo(filtered: RosterStudent[]) {
    const selected = filtered.find((item) => item.id === this.selectedId) ?? filtered[0];
    if (!selected) return `<div class="panel panel-pad"><div class="empty">暂无8班学生目录</div></div>`;
    const fields: ProfileField[] = Object.entries({ 姓名: selected.displayName, ...(this.profile ?? {}) }).map(([key, value]) => ({ key, label: key, value, sensitive: sensitiveProfileKeys.has(key) }));
    return `<div class="toolbar"><input class="input grow" data-student-search placeholder="搜索姓名、身份证件号、省学籍辅号或准考证号" value="${esc(this.query)}"><span class="muted">${filtered.length} 人</span></div><div class="profile-layout"><section class="panel"><div class="student-list">${filtered.map((student) => `<div class="student-row ${student.id === selected.id ? 'selected' : ''}" data-student-id="${esc(student.id)}"><span>${esc(student.displayName)}</span></div>`).join('')}</div></section><section class="panel panel-pad"><h3>${esc(selected.displayName)}</h3>${profileGroups.map((group) => { const groupFields = fields.filter((field) => group.keys.includes(field.key as never)); return groupFields.length ? `<div class="profile-section"><h4>${group.title}</h4><div class="field-grid">${groupFields.map((field) => `<div class="field"><label>${esc(field.label)}</label><div>${esc(maskProfileField(field, this.revealed.has(field.key)))} ${field.sensitive ? `<button class="button quiet small" data-reveal="${esc(field.key)}">${this.revealed.has(field.key) ? '隐藏' : '查看'}</button>` : ''}</div></div>`).join('')}</div></div>` : ''; }).join('') || '<div class="empty">档案暂不可用</div>'}</section></div>`;
  }
  private renderGroups() { const layout = this.draftGroupLayout || this.savedGroupLayout; const groups = layout?.groups || []; return this.renderImportShell('分组表', this.groupErrors, groups.length ? groups.map((group) => `<div class="group-row"><strong>第${group.groupIndex}组</strong>${group.members.map((member) => `<span class="${member.isLeader ? 'leader' : ''}">${esc(member.displayName)}</span>`).join('')}</div>`).join('') : '<div class="empty">暂无已保存分组表</div>', Boolean(this.draftGroupLayout), this.groupSaveState); }
  private renderSeating() { const layout = this.draftSeatingLayout || this.savedSeatingLayout; const body = layout ? `<div class="seating-grid" style="grid-template-columns:repeat(${layout.columnCount},minmax(0,1fr))">${layout.cells.map((cell) => `<div class="seat-cell ${cell.cellKind} ${cell.studentId ? 'occupied' : ''}">${esc(cell.cellKind === 'student' ? cell.displayName : cell.cellKind === 'podium' ? '讲台' : cell.cellKind === 'aisle' ? '过道' : '')}</div>`).join('')}</div>` : '<div class="empty">暂无已保存座次表</div>'; return this.renderImportShell('座次表', this.seatingErrors, body, Boolean(this.draftSeatingLayout), this.seatingSaveState); }
  private renderImportShell(title: string, errors: string[], body: string, hasDraft: boolean, saveState: 'idle' | 'saving' | 'saved' | 'error') { const status = saveState === 'saving' ? '<span class="muted">正在保存</span>' : saveState === 'saved' ? '<span class="muted">已保存</span>' : ''; return `<div class="toolbar"><button class="button" data-template-download>下载标准模板</button><label class="button quiet">上传 .xlsx<input type="file" accept=".xlsx" data-layout-file hidden></label><button class="button quiet" data-layout-print>打印 / PDF</button>${status}</div>${errors.length ? `<section class="panel panel-pad error-list"><h3>校验错误</h3><ul>${errors.map((error) => `<li>${esc(error)}</li>`).join('')}</ul></section>` : ''}<section class="panel panel-pad"><h3>${title}</h3>${body}</section>${hasDraft ? '<div class="toolbar"><button class="button" data-layout-confirm>确认保存</button><button class="button quiet" data-layout-cancel>取消</button></div>' : ''}`; }
  private async handleUpload(file?: File) { if (!file || file.name.toLowerCase().endsWith('.xlsx') === false) return; try { if (!window.XLSX) throw new Error('XLSX 解析器加载失败'); const workbook = window.XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheet = workbook.Sheets[workbook.SheetNames[0] || '']; if (!sheet) throw new Error('模板不包含工作表'); const rows = window.XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' }) as WorkbookRows; const classId = await this.repository.getClass8Id(); if (!classId) throw new Error('8班班级不存在'); const lookup = exactStudentLookup(this.students, classId); if (this.tab === 'groups') { const result = parseGroupTemplate(rows, lookup); this.draftGroupLayout = result.layout || null; this.groupErrors = result.errors; this.groupSaveState = result.errors.length ? 'error' : 'idle'; } else if (this.tab === 'seating') { const result = parseSeatingTemplate(rows, lookup); this.draftSeatingLayout = result.layout || null; this.seatingErrors = result.errors; this.seatingSaveState = result.errors.length ? 'error' : 'idle'; } } catch (error) { if (this.tab === 'groups') { this.draftGroupLayout = null; this.groupErrors = [(error as Error).message]; this.groupSaveState = 'error'; } else { this.draftSeatingLayout = null; this.seatingErrors = [(error as Error).message]; this.seatingSaveState = 'error'; } } this.render(); }
  private cancelCurrentDraft() { if (this.tab === 'groups') { this.draftGroupLayout = null; this.groupErrors = []; this.groupSaveState = 'idle'; } else if (this.tab === 'seating') { this.draftSeatingLayout = null; this.seatingErrors = []; this.seatingSaveState = 'idle'; } this.render(); }
  private async confirmLayout() { if (this.tab === 'groups') { const draft = this.draftGroupLayout; if (!draft || !this.groups) return; this.groupSaveState = 'saving'; this.groupErrors = []; this.render(); try { const classId = await this.repository.getClass8Id(); if (!classId) throw new Error('8班班级不存在'); await this.groups.replace(classId, draft); this.savedGroupLayout = draft; this.draftGroupLayout = null; this.groupSaveState = 'saved'; } catch (error) { this.groupSaveState = 'error'; this.groupErrors = [(error as Error).message]; } this.render(); return; } if (this.tab === 'seating') { const draft = this.draftSeatingLayout; if (!draft || !this.seating) return; this.seatingSaveState = 'saving'; this.seatingErrors = []; this.render(); try { const classId = await this.repository.getClass8Id(); if (!classId) throw new Error('8班班级不存在'); await this.seating.replace(classId, draft); this.savedSeatingLayout = draft; this.draftSeatingLayout = null; this.seatingSaveState = 'saved'; } catch (error) { this.seatingSaveState = 'error'; this.seatingErrors = [(error as Error).message]; } this.render(); } }
  private downloadTemplate(tab: string) { if (!window.XLSX) return; const rows = tab === 'groups' ? [['组别', '成员1', '成员2', '成员3', '成员4', '组长'], [1, '', '', '', '', ''], [2, '', '', '', '', '']] : [['模板版本', 1], ['行数', 8, '列数', 9], ...Array.from({ length: 8 }, (_, row) => Array.from({ length: 9 }, (_, column) => row === 0 ? 'PODIUM' : column === 4 ? 'AISLE' : 'EMPTY'))]; const book = window.XLSX.utils.book_new(); window.XLSX.utils.book_append_sheet(book, window.XLSX.utils.aoa_to_sheet(rows), '模板'); const blob = new Blob([window.XLSX.write(book, { bookType: 'xlsx', type: 'array' })], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = tab === 'groups' ? '2025级8班-分组表-v1.xlsx' : '2025级8班-座次表-v1.xlsx'; link.click(); URL.revokeObjectURL(link.href); }
  private printCurrent() { if (this.tab === 'groups') { const layout = this.draftGroupLayout || this.savedGroupLayout; if (layout) printLayout('2025级8班 分组表', `<div>${layout.groups.map((group) => `<p>${group.groupIndex}组：${group.members.map((member) => member.isLeader ? `<strong>${esc(member.displayName)}</strong>` : esc(member.displayName)).join('、')}</p>`).join('')}</div>`); } if (this.tab === 'seating') { const layout = this.draftSeatingLayout || this.savedSeatingLayout; if (layout) printLayout('2025级8班 座次表', `<div class="print-grid" style="grid-template-columns:repeat(${layout.columnCount},1fr)">${layout.cells.map((cell) => `<div class="print-cell">${esc(cell.displayName || cell.cellKind)}</div>`).join('')}</div>`); } }
}
